<a href="https://colab.research.google.com/github/jmbarrios/THC-Python/blob/main/20211109_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bibliotecas

In [1]:
!pip install rich

     |████████████████████████████████| 213 kB 13.9 MB/s 
     |████████████████████████████████| 51 kB 4.5 MB/s 


In [2]:
from rich import (print,
                  inspect)

# Numpy

In [3]:
import numpy as np

In [11]:
a = np.array([1, 2, 6, 9, 6, 4])
print(a)
print(type(a))
print(a.shape)

[1 2 6 9 6 4]

<class 'numpy.ndarray'>

(6,)

Quiero calcular el cuadrado de los primeros 100 naturales

In [5]:
l = range(10000000000000000)

In [6]:
%timeit [el**2 for el in l]

10000 loops, best of 5: 22.8 µs per loop


In [7]:
l = np.arange(100)

In [8]:
%timeit l**2

The slowest run took 132.46 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 968 ns per loop


Imagen en blanco y negro

de resolucion $2\times n$
$$
\begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1n}\\
a_{21} & a_{22} & \ldots & a_{2n}
\end{pmatrix}
$$

cada $a_{ij}\in \{0, 1, \ldots, 255\}$

In [9]:
2**8

256

In [10]:
b = np.array([
              [1, 2, 3, 4], 
              [6, 7, 8, 9]
              ])
print(b)
print(type(b))
print(b.shape)

[[1 2 3 4]
 [6 7 8 9]]

<class 'numpy.ndarray'>

(2, 4)

Mi arreglo `b` tiene 2 renglones y 4 columnas

Una imagen en color tiene tres imagenes uno para rojo, otra para verde y otra para azul.


In [12]:
c = np.array([
              [[1, 2, 3], [4, 5, 6]],
              [[4, 6, 7], [8, 9, 10]],
              [[1, 2, 8], [6, 7, 9]]
])
print(c)
print(type(c))
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 4  6  7]
  [ 8  9 10]]

 [[ 1  2  8]
  [ 6  7  9]]]

<class 'numpy.ndarray'>

(3, 2, 3)

`c` estaría representando una imagen de 3 canales(RGB) con 2 renglones y 3 columnas